# /etc/nginx/sites-available/dohongky-k24cntt3.conf
server {
    listen 80;
    listen [::]:80;

    server_name dohongky-k24cntt3;
    root /var/www/devops-hackathon-de006-dohongky-k24cntt3/src;
    index index.html;

    access_log /var/log/nginx/dohongky-k24cntt3.access.log;
    error_log /var/log/nginx/dohongky-k24cntt3.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
